-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 15:41:51 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classroom` ;

-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classroom` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_1` ;

CREATE TABLE IF NOT EXISTS `timestamps_1` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_2` ;

CREATE TABLE IF NOT EXISTS `timestamps_2` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_3` ;

CREATE TABLE IF NOT EXISTS `timestamps_3` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_4` ;

CREATE TABLE IF NOT EXISTS `timestamps_4` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_5`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_5` ;

CREATE TABLE IF NOT EXISTS `timestamps_5` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_6`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_6` ;

CREATE TABLE IF NOT EXISTS `timestamps_6` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');


-- -----------------------------------------------------
-- Table `timestamps_7`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_7` ;

CREATE TABLE IF NOT EXISTS `timestamps_7` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time`  NULL COMMENT '');

USE `classroom` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `username` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(20) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  `role` VARCHAR(20) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `password_UNIQUE` (`password` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lessons` ;

CREATE TABLE IF NOT EXISTS `lessons` (
  `idlessons` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(140) NOT NULL COMMENT '',
  `content` BLOB NOT NULL COMMENT '',
  `start_date` DATETIME NOT NULL COMMENT '',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idlessons`)  COMMENT '',
  UNIQUE INDEX `idlessons_UNIQUE` (`idlessons` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
