-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 11:17:08 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classroom` ;

-- -----------------------------------------------------
-- Schema classroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classroom` ;
USE `classroom` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
USE `classroom`;
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password`) VALUES (DEFAULT, 'Eric', 'eihli', 'ericihli@gmail.com', 'epass');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password`) VALUES (DEFAULT, 'Richard', 'rstanley', 'rstanley943@gmail.com', 'rpass');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password`) VALUES (DEFAULT, 'Devon', 'dharvey', 'devonharvey@gmail.com', 'dpass');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `password`) VALUES (DEFAULT, 'Jake', 'jlee', 'jake841lee@gmail.com', 'jpass');

COMMIT;

